index:
    path: /
    controller: App\Controller\Controller::index

doctor:
    path: /doctor
    methods: GET
    controller: App\Controller\Controller::doctor

createDoctor:
    path: /doctor
    methods: POST
    controller: App\Controller\Controller::createDoctor

slots:
    path: /slots/{doctorId}
    methods: GET
    controller: App\Controller\Controller::slots

createSlot:
    path: /slots/{doctorId}
    methods: POST
    controller: App\Controller\Controller::createSlot
